#!/system/bin/sh
# Created by broodplank1337
# broodROM Jellybean
# Release 3 (broodParts 3)

 
# broodParts Settings:
if [ -e /system/etc/broodrom/scaling_governor ]; then
	echo "Setting CPU Governor" 
        cat /system/etc/broodrom/scaling_governor > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
fi;

if [ -e /system/etc/broodrom/scaling_min_freq ]; then
	echo "Setting CPU Min Freq" 
        cat /system/etc/broodrom/scaling_min_freq > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
fi; 

if [ -e /system/etc/broodrom/scaling_max_freq ]; then
	echo "Setting CPU Max Freq" 
        cat /system/etc/broodrom/scaling_max_freq > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
fi;

if [ -e /system/etc/broodrom/scheduler ]; then
	echo "Setting I/O Scheduler" 
        export SCHEDPREF=`cat /system/etc/broodrom/scheduler`;
        echo ${SCHEDPREF} > /sys/block/mmcblk0/queue/scheduler
fi;

if [ -e /system/etc/broodrom/read_ahead_kb ]; then
	echo "Setting Read Ahead KB for SDCard" 
        cat /system/etc/broodrom/read_ahead_kb > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi;

if [ -e /system/etc/broodrom/adbnotify ]; then
	echo "Setting ADB Notification Icon" 
        export ADBPREF=`cat /system/etc/broodrom/adbnotify`; 
        setprop persist.adb.notify ${ADBPREF}
fi;

if [ -e /system/etc/broodrom/govtweak ]; then
	if [ "`cat /system/etc/broodrom/govtweak`" -eq 1 ]; then
	echo "Enabling CPU Governor Tweaks" 
        #===============================================================
	# Ondemand
	# ==============================================================
		if [ -e /sys/devices/system/cpu/cpu0/cpufreq/ondemand/up_threshold ]; then
			echo "Enabling Ondemand Tweaks" 
			echo "85" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/up_threshold;
			echo "10" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/down_differential;
		fi;		
		if [ -e /sys/devices/system/cpu/cpufreq/ondemand/up_threshold ]; then
			echo "85" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold;
			echo "10" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential;
		fi;		
	# ==============================================================
	# OndemandX
	# ==============================================================
		if [ -e /sys/devices/system/cpu/cpu0/cpufreq/ondemandx/up_threshold ]; then
			echo "Enabling Ondemandx Tweaks" 
			echo "85" > /sys/devices/system/cpu/cpu0/cpufreq/ondemandx/up_threshold;
			echo "10" > /sys/devices/system/cpu/cpu0/cpufreq/ondemandx/down_differential;
		fi;		
		if [ -e /sys/devices/system/cpu/cpufreq/ondemandx/up_threshold ]; then
			echo "Enabling Ondemandx Tweaks" 
			echo "85" > /sys/devices/system/cpu/cpufreq/ondemandx/up_threshold;
			echo "10" > /sys/devices/system/cpu/cpufreq/ondemandx/down_differential;
		fi;
	# ==============================================================
	# Conservative 
	# ==============================================================
		if [ -e /sys/devices/system/cpu/cpu0/cpufreq/conservative/up_threshold ]; then
			echo "Enabling Conservative Tweaks" 
			echo "85" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/up_threshold;
			echo "75" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/down_threshold;
			echo "100" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/freq_step;
		fi;		
		if [ -e /sys/devices/system/cpu/cpufreq/conservative/up_threshold ]; then
			echo "85" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold;
			echo "75" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold;
	       		echo "100" > /sys/devices/system/cpu/cpufreq/conservative/freq_step;
		fi;
	# ==============================================================
	# lulzactive 
	# ==============================================================
		if [ -e /sys/devices/system/cpu/cpufreq/lulzactive/inc_cpu_load ]; then
			echo "Enabling lulzactive Tweaks" 
			echo "85" > /sys/devices/system/cpu/cpufreq/lulzactive/inc_cpu_load;
			echo "1" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_down_step;
		fi;
	fi;
fi;



if [ -e /system/etc/broodrom/iotweak ]; then

	if [ "`cat /system/etc/broodrom/iotweak`" -eq 1 ]; then
		echo "Enabling I/O Scheduler Tweaks" 
		
		if [ -e /sys/block/mmcblk0/queue/rotational ]; 
		then
			echo 0 > /sys/block/mmcblk0/queue/rotational; 
		fi;
		if [ -e /sys/block/mmcblk0/queue/nr_requests ];
		then
			echo 1024 > /sys/block/mmcblk0/queue/nr_requests;
		fi;
		#CFQ specific
		if [ -e /sys/block/mmcblk0/queue/iosched/back_seek_penalty ];
		then 
			echo 1 > /sys/block/mmcblk0/queue/iosched/back_seek_penalty;
		fi;
		#CFQ specific
		if [ -e /sys/block/mmcblk0/queue/iosched/low_latency ];
		then
			echo 1 > /sys/block/mmcblk0/queue/iosched/low_latency;
		fi;
		#CFQ Specific
		if [ -e /sys/block/mmcblk0/queue/iosched/slice_idle ];
		then 
			echo 1 > /sys/block/mmcblk0/queue/iosched/slice_idle; 
		fi;
		# deadline/VR/SIO scheduler specific
		if [ -e /sys/block/mmcblk0/queue/iosched/fifo_batch ];
		then
			echo 4 > /sys/block/mmcblk0/queue/iosched/fifo_batch;
		fi;
		if [ -e /sys/block/mmcblk0/queue/iosched/writes_starved ];
		then
			echo 4 > /sys/block/mmcblk0/queue/iosched/writes_starved;
		fi;
		#CFQ specific
		if [ -e /sys/block/mmcblk0/queue/iosched/quantum ];
		then
			echo 8 > /sys/block/mmcblk0/queue/iosched/quantum;
		fi;
		#VR Specific
		if [ -e /sys/block/mmcblk0/queue/iosched/rev_penalty ];
		then
			echo 1 > /sys/block/mmcblk0/queue/iosched/rev_penalty;
		fi;
		if [ -e /sys/block/mmcblk0/queue/rq_affinity ];
		then
		echo "1"   >  /sys/block/mmcblk0/queue/rq_affinity;   
		fi;
		#disable iostats to reduce overhead  # idea by kodos96 - thanks !
		if [ -e /sys/block/mmcblk0/queue/iostats ];
		then
			echo "0" > /sys/block/mmcblk0/queue/iostats;
		fi;
	fi;
fi;

if [ -e /system/etc/broodrom/nettweak ]; then
	if [ "`cat /system/etc/broodrom/nettweak`" -eq 1 ]; then
		echo "Enabling Network Tweaks" 
		sysctl -w net.ipv4.tcp_timestamps=0;
		sysctl -w net.ipv4.tcp_tw_reuse=1;
		sysctl -w net.ipv4.tcp_sack=1;
		sysctl -w net.ipv4.tcp_dsack=1;
		sysctl -w net.ipv4.tcp_tw_recycle=1;
		sysctl -w net.ipv4.tcp_window_scaling=1;
		sysctl -w net.ipv4.tcp_keepalive_probes=5;
		sysctl -w net.ipv4.tcp_keepalive_intvl=30;
		sysctl -w net.ipv4.tcp_fin_timeout=30;
		sysctl -w net.ipv4.tcp_moderate_rcvbuf=1;
	fi;
fi;

if [ -e /system/etc/broodrom/vmtweak ]; then
	if [ "`cat /system/etc/broodrom/vmtweak`" -eq 1 ]; then
		echo "Enabling Dalvik Tweaks" 
		mem=`free|grep Mem | awk '{print $2}'`;
		totmem=`(echo - | awk -v A=$mem '{print A*1024;}')`;
		max=`(echo - | awk -v A=$totmem '{print A*75/100;}')`;
		page_size=`cat /proc/sys/kernel/shmmni`;
		all=`(echo - | awk -v A=$totmem -v B=$page_size '{print A*80/100/B}')`;
		sysctl -w kernel.sem="250 256000 32 1024";
		sysctl -w kernel.shmmax="$max";
		sysctl -w kernel.shmall="$all";
		sysctl -w vm.dirty_background_ratio=15;
		sysctl -w vm.dirty_ratio=30;
		sysctl -w vm.page-cluster=3;
		sysctl -w vm.laptop_mode=0;
		sysctl -w vm.dirty_expire_centisecs=3000;
		sysctl -w vm.dirty_writeback_centisecs=500;
		sysctl -w vm.vfs_cache_pressure=50;
		sysctl -w vm.overcommit_memory=1;
		sysctl -w vm.oom_kill_allocating_task=0;
	fi;
fi;
